<?php
	session_start();
	// funcion auxiliar para obtener la url de esta propia pagina.
	function url(){
	    /* QUITO PROTOCOL POR ERROR 406: "Not acceptable!. An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."
	    if(isset($_SERVER['HTTPS'])){
	        $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https:" : "http:";
	    }
	    else{
	        $protocol = 'http:';
	    }
	    return $protocol . "//" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
	    */
	    return "//" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
	}
	//$pagina_from = urlencode(url());

	// Recojo pagina FROM para devolver al lugar desde el que se ha logado. --> http://localhost/lvti-premium/modules/vl/login.php?from=%2Flvti-premium%2Fdemo5premium2.php
	if(isset($_GET['from'])) {
	    $pagina_from = htmlspecialchars($_GET['from']);
	}
	else {
	  if(isset($_GET['from_back'])) {
	    //$pagina_from = htmlspecialchars($_POST['from_back']);
	    $pagina_from = $_GET['from_back'];
	  }
	  elseif(isset($_POST['from_back'])) {
	    //$pagina_from = htmlspecialchars($_POST['from_back']);
	    $pagina_from = $_POST['from_back'];
	  }
	  // para páginas donde no hemos añadido el GET_from.
	  else {
	    //$pagina_from = "profile.php"; //"index.php";
	    $pagina_from = urlencode(url());
	  }
	}

	if(isset($_COOKIE['id']) && isset($_COOKIE['username']) && isset($_COOKIE['password'])){
		setcookie("id", '', strtotime('-30 days'), '/');
		setcookie("username", '', strtotime('-30 days'), '/');
		setcookie("password", '', strtotime('-30 days'), '/');
	}
	session_destroy();
	//echo $pagina_from;
	header("location: ".$pagina_from);
	die;